update workflow

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -19,25 +19,22 @@ jobs:
           mkdir -p data
 
           # Fetch Brent (Global/Middle East Benchmark)
-          curl -f "https://www.alphavantage.co/query?function=BRENT&interval=monthly&apikey={{ secrets.OIL_API_KEY }}" -o data/brent.json || echo '{"data":[]}' > data/brent.json
+          curl -f "https://www.alphavantage.co/query?function=BRENT&interval=daily&apikey={{ secrets.OIL_API_KEY }}" -o data/brent.json || echo '{"data":[]}' > data/brent.json
           sleep 2
 
           # Fetch WTI (US Benchmark)
-          curl -f "https://www.alphavantage.co/query?function=WTI&interval=monthly&apikey={{ secrets.OIL_API_KEY }}" -o data/wti.json || echo '{"data":[]}' > data/wti.json
+          curl -f "https://www.alphavantage.co/query?function=WTI&interval=daily&apikey={{ secrets.OIL_API_KEY }}" -o data/wti.json || echo '{"data":[]}' > data/wti.json
           sleep 2
 
           # Fetch Natural Gas (LNG Status)
-          curl -f "https://www.alphavantage.co/query?function=NATURAL_GAS&interval=monthly&apikey={{ secrets.OIL_API_KEY }}" -o data/gas.json || echo '{"data":[]}' > data/gas.json
-
-          # Only overwrite if the API returns a valid JSON (not an HTML error)
-          # curl -f "https://www.alphavantage.co/{{ secrets.OIL_API_KEY }}" -o data/oil_temp.json || echo "{}" > data/oil_temp.json
+          curl -f "https://www.alphavantage.co/query?function=NATURAL_GAS&interval=daily&apikey={{ secrets.OIL_API_KEY }}" -o data/gas.json || echo '{"data":[]}' > data/gas.json
 
           # Check if it contains an error message, if not, move it to the real file
-          if grep -q "Global Quote" data/brent.json; then
-            mv data/oil_temp.json data/oil.json
-          else
-            echo "API failed or returned error. Using placeholder."
-          fi
+          #if grep -q "Global Quote" data/brent.json; then
+          #  mv data/oil_temp.json data/oil.json
+          #else
+          #  echo "API failed or returned error. Using placeholder."
+          #fi
       - name: Validate JSON Files
         run: |
           # If any file contains HTML (starts with <), reset it to prevent Hugo crash
